### ISSUE TITLE
[BUG]1688 LINK doesnt show qcfinder button

### ISSUE THREAD

**Issue by muraroboy** [cachho/reparchive-browser-extension#60] opened 2023-05-15 03:09 UTC
https://detail.1688.com/offer/715159231531.html
Actually none of the links are showing the qc button. idk why
https://www.cssbuy.com/item-micro-4415766195
they had it minutes ago

**Comment by cachho** [comment] 2023-05-15 05:51
Hey it works for me.

Most likely you're on a timeout on qc.photos because you sent too many requests in a short time. I'll have the owner take a look.

I'll close this issue as there is nothing wrong with the extension / the code in this rep.

**Closed by cachho** 2023-05-15 05:51 UTC

**Comment by cachho** [comment] 2023-05-15 07:46
The owner of qc.photos disclosed the rate limit to me. I'm not going to share it publicly, that's up to him. 

The problem is that it's shared between all users. So you might not be able to see qc pics because lots of people are using the extension at the same time. So it might not even be you hitting the limit.

We're going to see if we can increase the rate limit.
